fix(scripts): condense mounts for effciency

diff --git a/system_files/usr/lib/subsystem/daemon/subsystem-filesystemd b/system_files/usr/lib/subsystem/daemon/subsystem-filesystemd
--- a/system_files/usr/lib/subsystem/daemon/subsystem-filesystemd
+++ b/system_files/usr/lib/subsystem/daemon/subsystem-filesystemd
@@ -1,8 +1,8 @@
 #!/bin/bash
 # SPDX-License-Identifier: GPL-3.0-only
 
-## set pipefail, errtrace
-set -o pipefail -o errtrace
+## set errexit, pipefail, errtrace
+set -eEo pipefail
 
 ## do our checks
 if [[ "$EUID" != "0" ]]; then
@@ -34,16 +34,16 @@ drop_user() {
 }
 
 userfs() {
-    local DIR HASH SUID_START SUID_RANGE SGID_START SGID_RANGE
+    local USERDIR HASH SUID_START SUID_RANGE SGID_START SGID_RANGE
 
     while read -r TARGETUSR; do
         case "$1" in
             mount)
                 if is_mounted "$TARGETUSR"; then
-                    echo "[-!-] Already mounted user subsystem rootfs for user $TARGETUSR."
+                    echo "[-!-] Already mounted rootfs for user $TARGETUSR."
                     continue
                 fi
-                echo "[---] Mounting user subsystem rootfs for user $TARGETUSR."
+                echo "[---] Mounting rootfs for user $TARGETUSR."
                 operational_users+=("$TARGETUSR")
 
                 read -r SUID_START SUID_RANGE <<< "$(awk -F: -v u="$TARGETUSR" '$1==u {print $2,$3}' /etc/subuid)"
@@ -55,46 +55,56 @@ userfs() {
                 fi
 
                 HASH=$(printf '%s%s' "$(</etc/machine-id)" "$TARGETUSR" | sha256sum | awk '{print $1}')
-                DIR=$RWLIBDIR/rootfs-rw/$HASH
+                USERDIR=$RWLIBDIR/$HASH
 
-                trap 'echo "[!!!] Failed to mount user subsystem rootfs for $TARGETUSR, aborting." && return 1' ERR
+                trap 'echo "[!!!] Failed to mount rootfs for $TARGETUSR, skipping." && continue' ERR
                 trap 'echo "[!!!] Received SIGTERM, stopping." && return 0' SIGTERM
 
-                echo "[1/3] Creating user subsystem rootfs."
-                mkdir -p "$DIR"/{rootfs,idmapped,data,.work}
-                chown -R "$TARGETUSR":"$TARGETUSR" "$DIR"/
+                echo "[1/4] Setting up rootfs directory."
+                rm -rf "${USERDIR:?}"/*
+                mkdir -p "$USERDIR"/{rootfs,base/{home,root,bin,sbin,lib,lib64,etc,var,opt,tmp,run,srv,sys,dev,proc},data,.work}
+                chown -R "$TARGETUSR":"$TARGETUSR" "$USERDIR"/
 
-                echo "[2/3] Idmapping base subsystem rootfs."
-                mount --beneath --map-users 0:"$SUID_START":"$SUID_RANGE" --map-groups 0:"$SGID_START":"$SGID_RANGE" -o ro,bind "$RWLIBDIR"/rootfs-ro "$DIR"/idmapped
+                echo "[2/4] Locking rootfs directory."
+                mount --bind -o ro "$USERDIR"/base "$USERDIR"/base
 
-                echo "[3/3] Mounting user subsystem rootfs overlay."
-                mount -t overlay overlay -o index=off,lowerdir="$DIR"/idmapped,upperdir="$DIR"/data,workdir="$DIR"/.work "$DIR"/rootfs
+                echo "[3/4] Mounting toplevel directories."
+                for dir in etc var; do mount --map-users 0:"$SUID_START":"$SUID_RANGE" --map-groups 0:"$SGID_START":"$SGID_RANGE" -o ro,acl,loop,user_xattr -t erofs "$ROLIBDIR"/segments/"$dir".dsk "$USERDIR"/base/"$dir"; done
+                for dir in srv opt; do mount --bind --map-users 0:"$SUID_START":"$SUID_RANGE" --map-groups 0:"$SGID_START":"$SGID_RANGE" -o ro /var/"$dir" "$USERDIR"/base/"$dir"; done
+                for type in "$USERDIR"/base/lib{,64}; do mount --bind --map-users 0:"$SUID_START":"$SUID_RANGE" --map-groups 0:"$SGID_START":"$SGID_RANGE" -o ro /usr/lib "$type"; done
+                for type in "$USERDIR"/base/{,s}bin; do mount --bind --map-users 0:"$SUID_START":"$SUID_RANGE" --map-groups 0:"$SGID_START":"$SGID_RANGE" -o ro /usr/bin "$type"; done
+
+                echo "[4/4] Mounting rootfs overlay."
+                mount -t overlay overlay -o index=off,lowerdir="$USERDIR"/base,upperdir="$USERDIR"/data,workdir="$USERDIR"/.work "$USERDIR"/rootfs
 
                 trap - ERR SIGTERM
                 ;;
 
             umount)
                 if ! is_mounted "$TARGETUSR"; then
-                    echo "[-!-] Already unmounted user subsystem rootfs for user $TARGETUSR."
+                    echo "[-!-] Already unmounted rootfs for user $TARGETUSR."
                     continue
                 fi
-                echo "[---] Unmounting user subsystem rootfs for user $TARGETUSR."
+                echo "[---] Unmounting rootfs for user $TARGETUSR."
                 drop_user "$TARGETUSR"
 
                 HASH=$(printf '%s%s' "$(</etc/machine-id)" "$TARGETUSR" | sha256sum | awk '{print $1}')
-                DIR=$RWLIBDIR/rootfs-rw/$HASH
+                USERDIR=$RWLIBDIR/$HASH
 
-                trap 'echo "[!!!] Failed to unmount user subsystem rootfs for $TARGETUSR, aborting." && return 1' ERR
+                trap 'echo "[!!!] Failed to unmount rootfs for $TARGETUSR, manual intervention is required." && continue' ERR
 
-                echo "[1/3] Unmounting user subsystem rootfs overlay."
-                umount -q "$DIR"/rootfs
+                echo "[1/4] Unmounting rootfs overlay."
+                umount -q "$USERDIR"/rootfs
 
-                echo "[2/3] Unmounting idmapped base subsystem rootfs."
-                umount -q "$DIR"/idmapped
+                echo "[2/4] Unmounting toplevel directories."
+                for dir in bin sbin lib lib64 etc var opt srv; do umount -q "$USERDIR"/base/"$dir"; done
 
-                echo "[3/3] Cleaning user subsystem rootfs."
-                rm -rf "${DIR:?}"/*
-                touch "$DIR"/user-inactive
+                echo "[3/4] Unlocking rootfs directory."
+                umount "$USERDIR"/base
+
+                echo "[4/4] Cleaning user subsystem rootfs."
+                rm -rf "${USERDIR:?}"/*
+                touch "$USERDIR"/user-inactive
 
                 trap - ERR
                 ;;
@@ -102,41 +112,11 @@ userfs() {
     done < <(awk -F: '$3 >= 1000 && $3 != 65534 {print $1}' /etc/passwd)
 }
 
-basefs() {
-    if [[ "$1" == "mount" ]]; then
-        echo "[---] Mounting base subsystem rootfs."
-    
-        echo "[1/3] Creating base subssytem rootfs."
-        rm -rf "$RWLIBDIR"/rootfs-ro/*
-        mkdir -p "$RWLIBDIR"/rootfs-ro/{home,root,bin,sbin,lib,lib64,etc,var,opt,tmp,run,srv,sys,dev,proc}
-    
-        echo "[2/3] Mounting nested filesystems."
-        for dir in etc var; do mount -o ro,acl,loop,user_xattr -t erofs "$ROLIBDIR"/segments/"$dir".dsk "$RWLIBDIR"/rootfs-ro/"$dir"; done
-        for dir in srv opt; do mount --bind -o ro /var/"$dir" "$RWLIBDIR"/rootfs-ro/"$dir"; done
-        for type in "$RWLIBDIR"/rootfs-ro/lib{,64}; do mount --bind -o ro /usr/lib "$type"; done
-        for type in "$RWLIBDIR"/rootfs-ro/{,s}bin; do mount --bind -o ro /usr/bin "$type"; done
-    
-        echo "[3/3] Locking base subsystem rootfs."
-        mount --bind -o ro "$RWLIBDIR"/rootfs-ro "$RWLIBDIR"/rootfs-ro
-    elif [[ "$1" == "umount" ]]; then
-        echo "[---] Unmounting base subsystem rootfs."
-    
-        echo "[1/3] Unlocking base subsystem rootfs."
-        umount -q "$RWLIBDIR"/rootfs-ro
-    
-        echo "[2/3] Unmounting nested filesystems."
-        for dir in bin sbin lib lib64 etc var opt srv; do umount -q "$RWLIBDIR"/rootfs-ro/"$dir"; done
-    
-        echo "[3/3] Cleaning base subsystem rootfs."
-        rm -rf "$RWLIBDIR"/rootfs-ro/*
-        touch "$RWLIBDIR"/rootfs-ro/system-inactive
-    fi
-}
-
 monitor() {
     trap 'kill "$NOTIFY_PID" 2>/dev/null; break' SIGTERM
 
     echo "[---] Monitoring for new users."
+
 
     while true; do
         inotifywait -e close_write /etc/passwd &
@@ -152,7 +132,7 @@ monitor() {
                 userfs mount
                 break
             fi
-        done < <(grep -vE "root|nobody|[^0-9][0-9]{1,3}[^0-9]|^[0-9]{1,3}$|^[0-9]{1,3}[^0-9]|[^0-9][0-9]{1,3}$" /etc/passwd | awk -F: '{print $1}')
+        done < <(awk -F: '$3 >= 1000 && $3 != 65534 {print $1}' /etc/passwd)
     done
 
     trap - SIGTERM
@@ -161,7 +141,6 @@ monitor() {
 ## main logic
 systemd-notify --status "Starting..."
 echo "[-+-] Starting up."
-basefs mount
 userfs mount
 
 systemd-notify --ready --status "Filesystems are mounted."
@@ -170,6 +149,5 @@ monitor
 systemd-notify --status "Stopping..."
 echo "[-+-] Shutting down."
 userfs umount
-basefs umount
 
 systemd-notify --status "Stopped."
