feat(subsystem): properly mount subsystem image store rw and implement containershell

diff --git a/system_files/mainsys/usr/libexec/rechunker-group-fix b/system_files/mainsys/usr/libexec/rechunker-group-fix
--- a/system_files/mainsys/usr/libexec/rechunker-group-fix
+++ b/system_files/mainsys/usr/libexec/rechunker-group-fix
@@ -1,2 +1,6 @@
 #!/bin/sh
+
+[ "$EUID" != "0" ] && echo "We are not root, abort!!" && exit 1
+
 cat /usr/lib/sysusers.d/*.conf | grep -e "^g" | grep -v -e "^#" | awk "NF" | awk '{print $2}' | grep -v -e "wheel" -e "root" -e "sudo" | xargs -I{} sed -i "/{}/d" $1
+echo "Fixed groups."
