feat(subsystem): use ostree to take a snapshot of rootfs

diff --git a/system_files/usr/lib/subsystem/bin/filesystem b/system_files/usr/lib/subsystem/bin/filesystem
--- a/system_files/usr/lib/subsystem/bin/filesystem
+++ b/system_files/usr/lib/subsystem/bin/filesystem
@@ -52,6 +52,11 @@ for arg in "$@"; do
             fi
             ;;
 
+        --hash=*)
+            HASH="${arg#*=}"
+            readonly HASH
+            ;;
+
         --rfsdir=*)
             RFSDIR="${arg#*=}"
             readonly RFSDIR
@@ -69,20 +74,47 @@ case $ACTION in
         # trap EXIT
         trap 'echo "[!!!] Error occured in mounting process, cleaning up." && pkexec /usr/lib/subsystem/bin/filesystem unmount --store="$RFSDIR" --user="$TARGETUSR"' EXIT
 
-        # ensure mountpoint exists
-        mkdir -p "$RFSDIR"/root
-        chown "$TARGETUSR":"$TARGETUSR" "$RFSDIR"
-
-        # (re)mount filesystem
-        if ! findmnt "$RFSDIR"/root >/dev/null; then
-            echo "[i] Mounting filesystem."
-            mount --map-users 0:"$USER_SUBUID_START":"$USER_SUBUID_RANGE" --map-groups 0:"$USER_SUBGID_START":"$USER_SUBGID_RANGE" -o ro,acl,loop,user_xattr -t erofs /usr/lib/subsystem/rootfs/rootfs.dsk "$RFSDIR"/root
+        # (re)mount base filesystem
+        if ! findmnt "$RFSDIR"/base >/dev/null; then
+            echo "[i] Mounting base filesystem."
+            mkdir -p "$RFSDIR"/base
+            chown -R "$TARGETUSR":"$TARGETUSR" "$RFSDIR"
+            mount --map-users 0:"$USER_SUBUID_START":"$USER_SUBUID_RANGE" --map-groups 0:"$USER_SUBGID_START":"$USER_SUBGID_RANGE" -o ro,acl,loop,user_xattr -t erofs /usr/lib/subsystem/rootfs/rootfs.dsk "$RFSDIR"/base
         else
-            echo "[i] Remounting filesystem."
-            umount -q "$RFSDIR"/root
-            mount --map-users 0:"$USER_SUBUID_START":"$USER_SUBUID_RANGE" --map-groups 0:"$USER_SUBGID_START":"$USER_SUBGID_RANGE" -o ro,acl,loop,user_xattr -t erofs /usr/lib/subsystem/rootfs/rootfs.dsk "$RFSDIR"/root
+            echo "[i] Remounting base filesystem."
+            umount -q "$RFSDIR"/base
+            mount --map-users 0:"$USER_SUBUID_START":"$USER_SUBUID_RANGE" --map-groups 0:"$USER_SUBGID_START":"$USER_SUBGID_RANGE" -o ro,acl,loop,user_xattr -t erofs /usr/lib/subsystem/rootfs/rootfs.dsk "$RFSDIR"/base
         fi
 
+        # initialize ostree repo and commit rootfs if needed
+        if [[ ! -d "/var/lib/subsystem/repo/$HASH" ]]; then
+            echo "[i] Initializing rootfs repository."
+            mkdir -p /var/lib/subsystem/repo/"$HASH"
+            chown "$TARGETUSR":"$TARGETUSR" /var/lib/subsystem/repo/"$HASH"
+            ostree --repo="/var/lib/subsystem/repo/$HASH" init --mode=bare
+            ostree --repo="/var/lib/subsystem/repo/$HASH" commit --branch="subsystem-$TARGETUSR" --subject="subsystem snapshot for $TARGETUSR" "$RFSDIR"/base
+        fi
+
+        # clean checkout destination to ensure checkout accuracy
+        if [[ -d "/var/lib/subsystem/content/$HASH" ]]; then
+            echo "[i] Cleaning previous checkout."
+            rm -rf /var/lib/subsystem/content/"$HASH"/*
+        else
+            echo "[i] Creating checkout destination."
+            mkdir -p /var/lib/subsystem/content/"$HASH"/
+            chown "$TARGETUSR":"$TARGETUSR" /var/lib/subsystem/content/"$HASH"
+        fi
+
+        # checkout commit
+        echo "[i] Checking out and mounting rootfs."
+        ostree --repo="/var/lib/subsystem/repo/$HASH" checkout -H "subsystem-$TARGETUSR" /var/lib/subsystem/content/"$HASH"
+        mount -o ro,bind /var/lib/subsystem/content/"$HASH" /var/lib/subsystem/content/"$HASH"
+
+        # cleanup
+        echo "[i] Cleaning up."
+        umount -q "$RFSDIR"/base
+        rm -rf "$RFSDIR"/base
+        
         # reset traps
         trap - EXIT
         ;;
@@ -91,20 +123,23 @@ case $ACTION in
         trap 'echo "[!!!] Error occured in unmounting process, manual intervention is required."' EXIT
 
         # unmount filesystem
-        if findmnt "$RFSDIR"/root >/dev/null; then
-            echo "[i] Unmounting filesystem."
-            umount -q "$RFSDIR"/root
-            rm -rf "$RFSDIR"
+        if findmnt /var/lib/subsystem/content/"$HASH" >/dev/null; then
+            echo "[i] Unmounting rootfs."
+            umount -q /var/lib/subsystem/content/"$HASH"
         else 
             echo "[!!] Filesystem appears to be unmounted already, ignoring."
         fi
+
+        # cleanup
+        echo "[i] Cleaning up."
+        rm -rf /var/lib/subsystem/content/"$HASH"/*
 
         # reset traps
         trap - EXIT
         ;;
     *)
         echo "[!!!] No action defined."
-        echo "[---] Usage: $0 mount|unmount --user=USER --rfsdir=PATH/TO/RFSDIR"
+        echo "[---] Usage: $0 mount|unmount --user=USER --hash=HASH --rfsdir=PATH/TO/RFSDIR"
         exit 64
         ;;
 esac
