chore(scripts): handle EXIT signal

diff --git a/system_files/usr/lib/subsystem/bin/filesystem b/system_files/usr/lib/subsystem/bin/filesystem
--- a/system_files/usr/lib/subsystem/bin/filesystem
+++ b/system_files/usr/lib/subsystem/bin/filesystem
@@ -25,6 +25,7 @@ for arg in "$@"; do
             MSDIR="${arg#*=}"
             readonly MSDIR
             ;;
+
         --user=*)
             TARGETUSR="${arg#*=}"
             USER_SUBUID=$(grep "^$TARGETUSR:" /etc/subuid | cut -d: -f2)
@@ -32,16 +33,19 @@ for arg in "$@"; do
             readonly USER_SUBUID
             readonly USER_SUBGID
             ;;
+
         mount)
             [[ "$arg" != "$1" ]] && continue
             ACTION=mount
             readonly ACTION
             ;;
+
         unmount)
             [[ "$arg" != "$1" ]] && continue
             ACTION=unmount
             readonly ACTION
             ;;
+
         *)
             echo "[i] Argument $arg not known, ignoring."
             ;;
@@ -57,6 +61,10 @@ fi
 # run mount/unmount action
 case $ACTION in
     mount)
+        # trap EXIT
+        trap 'echo "[!!!] Error occured in mounting process, cleaning up." && pkexec /usr/lib/subsystem/bin/filesystem unmount --store="$MSDIR" --user="$TARGETUSR"' EXIT
+
+        # (re)mount lower filesystem
         if ! findmnt "$MSDIR"/basefs >/dev/null; then
             echo "[---] Mounting lower filesystem."
             mount --map-users 0:"$USER_SUBUID":1 --map-groups 0:"$USER_SUBGID":1 -o ro,acl,loop,user_xattr -t erofs /usr/lib/subsystem/rootfs/rootfs.dsk "$MSDIR/basefs"
@@ -66,6 +74,8 @@ case $ACTION in
             umount -q "$MSDIR"/basefs
             mount --map-users 0:"$USER_SUBUID":1 --map-groups 0:"$USER_SUBGID":1 -o ro,acl,loop,user_xattr -t erofs /usr/lib/subsystem/rootfs/rootfs.dsk "$MSDIR/basefs"
         fi
+
+        # (re)mount upper filesystem
         if ! findmnt "$MSDIR"/rootfs >/dev/null; then
             echo "[---] Mounting upper filesystem."
             mount -t overlay overlay -o index=off,lowerdir="$MSDIR"/basefs,upperdir="$MSDIR"/fsdata,workdir="$MSDIR"/.work "$MSDIR"/rootfs
@@ -75,22 +85,35 @@ case $ACTION in
             umount -q "$MSDIR"/rootfs
             mount -t overlay overlay -o index=off,lowerdir="$MSDIR"/basefs,upperdir="$MSDIR"/fsdata,workdir="$MSDIR"/.work "$MSDIR"/rootfs
         fi
+
+        # reset traps
+        trap - EXIT
         ;;
     unmount)
+        # trap EXIT
+        trap 'echo "[!!!] Error occured in unmounting process, manual intervention is required."' EXIT
+
+        # unmount upper filesystem
         if findmnt "$MSDIR"/rootfs >/dev/null; then
             echo "[---] Unmounting upper filesystem."
             fuser -mk -15 "$MSDIR"/rootfs || true
             umount -q "$MSDIR"/rootfs
         fi
+
+        # unmount lower filesystem
         if findmnt "$MSDIR"/basefs >/dev/null; then
             echo "[---] Unmounting lower filesystem."
             fuser -mk -15 "$MSDIR"/basefs || true
             umount -q "$MSDIR"/basefs
         fi
+
+        # reset traps
+        trap - EXIT
         ;;
     *)
         echo "[!!!] No action defined."
         exit 1
+        ;;
 esac
 
 exit 0
