fix(scripts): handle invalid/no args

diff --git a/system_files/usr/lib/subsystem/bin/subsys b/system_files/usr/lib/subsystem/bin/subsys
--- a/system_files/usr/lib/subsystem/bin/subsys
+++ b/system_files/usr/lib/subsystem/bin/subsys
@@ -69,4 +69,16 @@ case $1 in
 
         # notify user of changes
         echo "[-i-] Subsystem disabled. Log out and back in to apply changes."
+        ;;
+    *)
+        # check for no argument or invalid argument
+        if [[ -z "$*" ]]; then
+            echo "[!!!] No command provided."
+        else
+            echo "[!!!] Invalid argument."
+        fi
+
+        # how to write good comments?
+        help
+        exit 1
 esac
