feat(scripts): rework mount logic

diff --git a/system_files/usr/lib/subsystem/bin/subsystem b/system_files/usr/lib/subsystem/bin/subsystem
--- a/system_files/usr/lib/subsystem/bin/subsystem
+++ b/system_files/usr/lib/subsystem/bin/subsystem
@@ -4,8 +4,31 @@
 # set errexit & pipefail
 set -eo pipefail
 
+# do our checks
+if [[ -z $1 ]]; then
+    echo "[!!!] Insufficient parameters."
+    echo "[---] Usage: $0 start|stop"
+    exit 64
+elif [[ "$EUID" == "0" ]]; then
+    echo "[!!!] Please do not run this as an administrator."
+    exit 77
+elif ! grep -q "$USER" /etc/subuid || ! grep -q "$USER" /etc/subgid; then
+    echo "[!!!] $USER does not have sub{uid,gid}s configured."
+    exit 78
+elif [[ -z $PODMAN_SYSTEMD_UNIT ]]; then
+    echo "[!!!] Environment isn't properly set up."
+    exit 71
+fi
+
+# set constants
+MSDIR="$HOME/.local/share/subsystem"
+SUBSYS_ID=$(echo -n "$(cat /etc/machine-id)$USER" | sha256sum | awk '{print $1}')
+readonly MSDIR
+readonly SUBSYS_ID
+
 # utilities
 start-subsystem() {
+    podman container rm -ifv "subsystem-$SUBSYS_ID"
     podman container run \
         --init \
         --rm \
@@ -30,50 +53,27 @@ start-subsystem() {
         /usr/libexec/ignition
 }
 
-# do our checks
-if [[ -z $1 ]]; then
-    echo "[!!!] Insufficient parameters."
-    echo "[---] Usage: $0 start|stop"
-    exit 64
-elif [[ "$EUID" == "0" ]]; then
-    echo "[!!!] Please do not run this as an administrator."
-    exit 77
-elif ! grep -q "$USER" /etc/subuid || ! grep -q "$USER" /etc/subgid; then
-    echo "[!!!] $USER does not have sub{uid,gid}s configured."
-    exit 78
-elif [[ -z $PODMAN_SYSTEMD_UNIT ]]; then
-    echo "[!!!] Environment isn't properly set up."
-    exit 71
-fi
-
-# set constants
-MSDIR="$HOME/.local/share/subsystem"
-SUBSYS_ID=$(echo -n "$(cat /etc/machine-id)$USER" | sha256sum | awk '{print $1}')
-readonly MSDIR
-readonly SUBSYS_ID
-
 # iterate through args
 case $1 in
     start)
         # trap EXIT
-        trap 'echo "[!!!] Error occurred, cleaning up." && systemd-notify --status="Start process failed." && /usr/lib/subsystem/bin/subsystem stop' EXIT
+        trap 'echo "[!!!] Error occurred, cleaning up." && /usr/lib/subsystem/bin/subsystem stop' EXIT
 
         # mount subsystem root
         echo "[1/3] Mounting subsystem root..."
-        pkexec /usr/lib/subsystem/bin/filesystem mount --store="$MSDIR" --user="$USER"
+        pkexec /usr/lib/subsystem/bin/filesystem mount --store="$MSDIR" --user="$USER" | cat
         echo "[1/3] Mounted subsystem root."
 
         # start subsystem
         echo "[2/3] Starting subsystem..."
         mkdir -p "$HOME"/.config/subsystem
-        podman container rm -ifv "subsystem-$SUBSYS_ID"
         start-subsystem
         echo "[2/3] Started subsystem."
 
         # dispatch restart helper
         echo "[3/3] Dispatching restart helper."
         touch "$MSDIR"/.keepalive.lock
-        systemd-cat /usr/lib/subsystem/bin/restart-helper --lockfile="$MSDIR/.keepalive.lock" --subsysid="$SUBSYS_ID"
+        /usr/lib/subsystem/bin/restart-helper --lockfile="$MSDIR/.keepalive.lock" --subsysid="$SUBSYS_ID" | cat
 
         # reset traps
         trap - EXIT
@@ -81,7 +81,7 @@ case $1 in
 
     stop)
         # trap failure incase stopping fails
-        trap 'echo "[!!!] Stop process failed. Manual intervention may be required." && systemd-notify --status="Stop process failed."' EXIT
+        trap 'echo "[!!!] Stop process failed. Manual intervention may be required."' EXIT
 
         # stop subsystem
         echo "[1/2] Stopping subsystem..."
@@ -92,7 +92,7 @@ case $1 in
 
         # unmount subsystem root
         echo "[2/2] Unmounting subsystem root..."
-        pkexec /usr/lib/subsystem/bin/filesystem unmount --store="$MSDIR" --user="$USER"
+        pkexec /usr/lib/subsystem/bin/filesystem unmount --store="$MSDIR" --user="$USER" | cat
         echo "[2/2] Unmounted subsystem root."
 
         # reset trap
@@ -102,7 +102,7 @@ case $1 in
     *)
         # you fool! you didn't pass the correct argument, dammit! you utter fool!
         echo "[!!!] Unrecognized argument $1."
-        echo "[i] Usage: $0 start|stop"
+        echo "[---] Usage: $0 start|stop"
         exit 64
         ;;
 esac
