feat(subsystem): go full userspace and eliminate dependency on external 'subsys' user

diff --git a/system_files/usr/libexec/run-as-all-human-users b/system_files/usr/libexec/run-as-all-human-users
--- a/system_files/usr/libexec/run-as-all-human-users
+++ b/system_files/usr/libexec/run-as-all-human-users
@@ -1,15 +1,16 @@
 #!/bin/bash
 
-if [ -z "$1" ]; then
+[[ "$EUID" != "0" ]] && echo "We are not root, abort!!" && exit 1
+
+if [[ -z "$1" ]]; then
     echo "Usage: $0 'command to run'"
     exit 1
 fi
 
 for user in /var/home/*; do
     username=$(basename "$user")
-    user_uid=$(id -u "$username")
-
     if getent passwd "$username" >/dev/null 2>&1; then
+        user_uid=$(id -u "$username")
         if [[ $user_uid -ge 1000 ]]; then
             echo "Executing '$1' as $username, uid $user_uid"
             su - "$username" -c "$1"
